/*
-- Query: SELECT * FROM people.car
LIMIT 0, 1000

-- Date: 2022-03-08 17:25
*/
INSERT INTO `` (`CAR_ID`,`BRAND`,`COLOR`,`PERSON_ID`,`TRANSMISSION`,`MOTOR_TYPE`) VALUES (1,'BMW','Red',1,'AUTO','DIESEL');
INSERT INTO `` (`CAR_ID`,`BRAND`,`COLOR`,`PERSON_ID`,`TRANSMISSION`,`MOTOR_TYPE`) VALUES (2,'VOLVO','Black',1,'MANUAL','PETROL');
