/*
-- Query: SELECT * FROM people.car
LIMIT 0, 1000

-- Date: 2022-03-08 16:02
*/
INSERT INTO `` (`CAR_ID`,`BRAND`,`COLOR`,`TRANSMISSION`,`MOTOR_TYPE`,`PERSON_ID`) VALUES (1,'MERCEDES','Black','AUTO','ELECTRIC',1);
INSERT INTO `` (`CAR_ID`,`BRAND`,`COLOR`,`TRANSMISSION`,`MOTOR_TYPE`,`PERSON_ID`) VALUES (2,'BMW','Red','AUTO','DIESEL',1);
