/*
-- Query: SELECT * FROM people.job
LIMIT 0, 1000

-- Date: 2022-03-08 16:02
*/
INSERT INTO `` (`JOB_ID`,`JOB_TITLE`,`SALARY`,`JOB_TYPE`) VALUES (1,'Java Developer',1200,'FULL-TIME');
INSERT INTO `` (`JOB_ID`,`JOB_TITLE`,`SALARY`,`JOB_TYPE`) VALUES (2,'Project Engineer',800,'FULL-TIME');
INSERT INTO `` (`JOB_ID`,`JOB_TITLE`,`SALARY`,`JOB_TYPE`) VALUES (3,'Driver',450,'PART-TIME');
